use std::sync::{Mutex, OnceLock};

use dusk_bytes::{DeserializableSlice, Serializable};
use dusk_core::transfer::phoenix::{TxCircuit, TxCircuitVec, NOTES_TREE_DEPTH};
use dusk_plonk::prelude::{PlonkVersion, Proof, Prover, Verifier};
use rand_chacha::ChaCha20Rng;
use rand_core::SeedableRng;
use serde::{Deserialize, Serialize};

#[cfg(all(target_arch = "wasm32", feature = "wasm-rayon"))]
pub use wasm_bindgen_rayon::init_thread_pool;

static PROVER: OnceLock<Mutex<Option<Prover>>> = OnceLock::new();
static VERIFIER: OnceLock<Mutex<Option<Verifier>>> = OnceLock::new();

#[derive(Debug, Serialize)]
struct InitResponse {
    ready: bool,
}

#[derive(Debug, Deserialize)]
struct ProveRequest {
    seed_hex: String,
    tx_circuit_vec_hex: String,
}

#[derive(Debug, Serialize)]
struct ProveResponse {
    proof_hex: String,
    public_inputs_hex: String,
    input_notes: usize,
}

#[derive(Debug, Deserialize)]
struct VerifyRequest {
    proof_hex: String,
    public_inputs_hex: String,
}

#[derive(Debug, Serialize)]
struct VerifyResponse {
    verified: bool,
}

#[no_mangle]
pub extern "C" fn plonkweb_alloc(len: usize) -> *mut u8 {
    plonkwasm::wasm::alloc(len)
}

#[no_mangle]
/// # Safety
///
/// `ptr` and `len` must describe a buffer previously returned by
/// `plonkweb_alloc` and not already freed.
pub unsafe extern "C" fn plonkweb_free(ptr: *mut u8, len: usize) {
    unsafe { plonkwasm::wasm::free(ptr, len) };
}

#[no_mangle]
/// Loads the transfer prover and verifier keys into wasm memory.
///
/// The prover key uses `Prover::try_from_trusted_unchecked_bytes`, which skips
/// commit-key point validation. This artifact is for trusted local benchmark
/// keys generated by Rusk, not user-supplied prover-key bytes.
///
/// # Safety
///
/// Pointer and length pairs must describe valid readable key buffers for the
/// duration of this call.
pub unsafe extern "C" fn plonkweb_init(
    prover_key_ptr: *const u8,
    prover_key_len: usize,
    verifier_key_ptr: *const u8,
    verifier_key_len: usize,
) -> u64 {
    let prover_key = unsafe { core::slice::from_raw_parts(prover_key_ptr, prover_key_len) };
    let verifier_key = unsafe { core::slice::from_raw_parts(verifier_key_ptr, verifier_key_len) };

    plonkwasm::wasm::respond(init(prover_key, verifier_key))
}

#[no_mangle]
/// Computes a Phoenix transfer proof from a JSON request.
///
/// The request must contain `seed_hex` and `tx_circuit_vec_hex`; the circuit
/// shape is selected from the serialized `TxCircuitVec` input-note count.
///
/// # Safety
///
/// `request_ptr` and `request_len` must describe a valid readable request
/// buffer for the duration of this call.
pub unsafe extern "C" fn plonkweb_prove(request_ptr: *const u8, request_len: usize) -> u64 {
    unsafe { plonkwasm::wasm::respond_from_request(request_ptr, request_len, prove_transfer) }
}

#[no_mangle]
/// Verifies a Phoenix transfer proof from a JSON request.
///
/// # Safety
///
/// `request_ptr` and `request_len` must describe a valid readable request
/// buffer for the duration of this call.
pub unsafe extern "C" fn plonkweb_verify(request_ptr: *const u8, request_len: usize) -> u64 {
    unsafe { plonkwasm::wasm::respond_from_request(request_ptr, request_len, verify_transfer) }
}

fn init(prover_key: &[u8], verifier_key: &[u8]) -> Result<InitResponse, String> {
    let prover =
        Prover::try_from_trusted_unchecked_bytes(prover_key).map_err(|err| format!("{err:?}"))?;
    let verifier = Verifier::try_from_bytes(verifier_key).map_err(|err| format!("{err:?}"))?;

    let prover_storage = PROVER.get_or_init(|| Mutex::new(None));
    *prover_storage
        .lock()
        .map_err(|_| "cached prover mutex is poisoned".to_string())? = Some(prover);

    let verifier_storage = VERIFIER.get_or_init(|| Mutex::new(None));
    *verifier_storage
        .lock()
        .map_err(|_| "cached verifier mutex is poisoned".to_string())? = Some(verifier);

    Ok(InitResponse { ready: true })
}

fn prove_transfer(request: &[u8]) -> Result<ProveResponse, String> {
    let request: ProveRequest =
        serde_json::from_slice(request).map_err(|err| format!("invalid prove request: {err}"))?;
    let seed = plonkwasm::wasm::decode_seed(&request.seed_hex)?;
    let tx_circuit_vec = plonkwasm::wasm::decode_hex(&request.tx_circuit_vec_hex)?;

    prove_transfer_bytes(&tx_circuit_vec, seed)
}

fn prove_transfer_bytes(
    tx_circuit_vec_bytes: &[u8],
    seed: [u8; 32],
) -> Result<ProveResponse, String> {
    let tx_circuit_vec =
        TxCircuitVec::from_slice(tx_circuit_vec_bytes).map_err(|err| format!("{err:?}"))?;
    let input_notes = tx_circuit_vec.input_notes_info.len();
    let mut rng = ChaCha20Rng::from_seed(seed);

    let prover_storage = PROVER
        .get()
        .ok_or_else(|| "plonkweb init must be called before prove".to_string())?;
    let prover_guard = prover_storage
        .lock()
        .map_err(|_| "cached prover mutex is poisoned".to_string())?;
    let prover = prover_guard
        .as_ref()
        .ok_or_else(|| "plonkweb init must be called before prove".to_string())?;

    let (proof, public_inputs) = match input_notes {
        1 => {
            let circuit = create_circuit::<1>(tx_circuit_vec)?;
            prover.prove_with_version(&mut rng, &circuit, PlonkVersion::V3)
        }
        2 => {
            let circuit = create_circuit::<2>(tx_circuit_vec)?;
            prover.prove_with_version(&mut rng, &circuit, PlonkVersion::V3)
        }
        3 => {
            let circuit = create_circuit::<3>(tx_circuit_vec)?;
            prover.prove_with_version(&mut rng, &circuit, PlonkVersion::V3)
        }
        4 => {
            let circuit = create_circuit::<4>(tx_circuit_vec)?;
            prover.prove_with_version(&mut rng, &circuit, PlonkVersion::V3)
        }
        _ => return Err(format!("unsupported input note count: {input_notes}")),
    }
    .map_err(|err| format!("{err:?}"))?;

    Ok(ProveResponse {
        proof_hex: plonkwasm::wasm::encode_hex(&proof.to_bytes()),
        public_inputs_hex: plonkwasm::wasm::encode_hex(&plonkwasm::serialize_public_inputs(
            &public_inputs,
        )),
        input_notes,
    })
}

fn verify_transfer(request: &[u8]) -> Result<VerifyResponse, String> {
    let request: VerifyRequest =
        serde_json::from_slice(request).map_err(|err| format!("invalid verify request: {err}"))?;
    let proof = plonkwasm::wasm::decode_hex(&request.proof_hex)?;
    let public_inputs = plonkwasm::wasm::decode_hex(&request.public_inputs_hex)?;

    verify_transfer_bytes(&proof, &public_inputs)
}

fn verify_transfer_bytes(proof: &[u8], public_inputs: &[u8]) -> Result<VerifyResponse, String> {
    let proof = Proof::from_slice(proof).map_err(|err| format!("invalid proof bytes: {err:?}"))?;
    let public_inputs = plonkwasm::deserialize_public_inputs(public_inputs)?;

    let verifier_storage = VERIFIER
        .get()
        .ok_or_else(|| "plonkweb init must be called before verify".to_string())?;
    let verifier_guard = verifier_storage
        .lock()
        .map_err(|_| "cached verifier mutex is poisoned".to_string())?;
    let verifier = verifier_guard
        .as_ref()
        .ok_or_else(|| "plonkweb init must be called before verify".to_string())?;

    verifier
        .verify_with_version(&proof, &public_inputs, PlonkVersion::V3)
        .map_err(|err| format!("{err:?}"))?;

    Ok(VerifyResponse { verified: true })
}

fn create_circuit<const I: usize>(
    tx_circuit_vec: TxCircuitVec,
) -> Result<TxCircuit<NOTES_TREE_DEPTH, I>, String> {
    Ok(TxCircuit {
        input_notes_info: tx_circuit_vec
            .input_notes_info
            .try_into()
            .map_err(|err| format!("{err:?}"))?,
        output_notes_info: tx_circuit_vec.output_notes_info,
        payload_hash: tx_circuit_vec.payload_hash,
        root: tx_circuit_vec.root,
        deposit: tx_circuit_vec.deposit,
        max_fee: tx_circuit_vec.max_fee,
        sender_pk: tx_circuit_vec.sender_pk,
        signatures: tx_circuit_vec.signatures,
    })
}
